/** Represents a row in the sessions table */
export interface SessionRow {
  id_user: string;
  session: string;
  expiresBool: string;
  expiresInt: number;
}

/**
 * Function to create a session, which returns an encrypted string to be used as a cookie
 * @param id_user - User identifier
 * @param max_age - Optional time in seconds before the session expires (defaults to one year)
 * @param persist - Whether to persist it to disk (default is true)
 * @returns Encrypted cookie key
 */
export interface CreateFunction {
  (id_user: string, max_age?: number, persist?: boolean): Promise<string>;
}

/**
 * Function to check whether a cookie is valid
 * @param cookie_key - Cookie key generated by `create`
 * @returns The `id_user` if the session is valid, or `false` if it is not
 */
export interface ConfirmFunction {
  (cookie_key: string): Promise<string | false>;
}

/**
 * Main function that provides the session system
 * @param secretManaggerKey - Secret key for encryption
 * @param dirdata - Directory for storing the database
 * @param dbname - Name of the database file
 * @returns An object with the `create` and `confirm` functions
 */
export interface UseLekSessionsFunction {
  (
    secretManaggerKey: string,
    dirdata?: string,
    dbname?: string
  ): {
    create: CreateFunction;
    confirm: ConfirmFunction;
  };
}